# Generated by Django 5.1.3 on 2024-11-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milheiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='custo_ponto',
            field=models.FloatField(default=0, verbose_name='Custo por Ponto'),
        ),
    ]
