# Generated by Django 5.1.3 on 2024-11-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milheiro', '0003_alter_plataforma_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carteiradepontos',
            options={'verbose_name_plural': 'Carteira de Pontos'},
        ),
    ]
