# Generated by Django 5.1.3 on 2024-11-27 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milheiro', '0004_alter_carteiradepontos_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteiradepontos',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dono dos Pontos'),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
