# Generated by Django 5.1.3 on 2024-11-29 01:46

import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milheiro', '0005_alter_carteiradepontos_pessoa_delete_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteiradepontos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carteiradepontos',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='carteiradepontos',
            name='data_aquisicao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Aquisição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carteiradepontos',
            name='data_expiracao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Expiração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carteiradepontos',
            name='descricao',
            field=models.CharField(default='', max_length=200, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carteiradepontos',
            name='custo_milheiro',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('valor'), '*', models.Value(1000)), '/', models.F('pontos')), output_field=models.FloatField()),
        ),
    ]
